name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-close: 30
          close-issue-message: "This issue was closed because it has been inactive for 30 days."
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
